import type { Metadata } from "next";
import '../styles/global.css';
import '../styles/variables.css';
import './top.css';

import Navigation from '../components/navigation/navigation';
import Header from '../components/header/header';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="body">
        <Navigation />
        <div className="main-contents">
          <Header />
          <main className="main">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
